name: qdmodel-base
channels:
  - defaults
dependencies:
  - python>3.7
  - pip
  - numpy
  - scipy
  - matplotlib
  - h5py
  - jupyter
  - plotly
  - pandas
  - pymysql
  - pip:
      - defusedxml
      - spe2py
      - untangle
